import { ChangeEvent, useEffect, useState, type ReactNode } from 'react'
import { supabase } from './lib/supabase'
import * as defaults from './data/anniversary'

type Content = { couple: typeof defaults.couple; milestones: typeof defaults.milestones; places: typeof defaults.places; months: typeof defaults.months; achievements: string[][]; reasons: string[]; commits: string[][]; letter: string }
const initial: Content = { couple: defaults.couple, milestones: defaults.milestones, places: defaults.places, months: defaults.months, achievements: defaults.achievements, reasons: defaults.reasons, commits: defaults.commits, letter: defaults.letter }
const sections = [['settings','⚙️','Налаштування'],['milestones','💍','Наша історія'],['months','📸','Спогади'],['places','🗺️','Місця'],['achievements','🏆','Досягнення'],['reasons','❤️','Чому я тебе люблю'],['commits','💻','Git log'],['letter','💌','Лист']] as const
const clone = <T,>(x: T): T => JSON.parse(JSON.stringify(x))

export default function Admin() {
  const [session, setSession] = useState(false), [tab, setTab] = useState<(typeof sections)[number][0]>('settings'), [content, setContent] = useState<Content>(clone(initial)), [status, setStatus] = useState(''), [email, setEmail] = useState(''), [password, setPassword] = useState('')
  useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({ data }) => setSession(!!data.session)); const { data: sub } = supabase.auth.onAuthStateChange((_, s) => setSession(!!s)); return () => sub.subscription.unsubscribe() }, [])
  useEffect(() => { if (!supabase || !session) return; supabase.from('site_content').select('content').eq('id','main').maybeSingle().then(({ data }) => data?.content && setContent(data.content as Content)) }, [session])
  useEffect(() => { const beforeUnload = (event: BeforeUnloadEvent) => { if (status === 'Є незбережені зміни') { event.preventDefault(); event.returnValue = '' } }; addEventListener('beforeunload', beforeUnload); return () => removeEventListener('beforeunload', beforeUnload) }, [status])
  const change = (next: Content) => { setContent(next); setStatus('Є незбережені зміни') }
  const save = async () => { if (!supabase) return setStatus('Додайте Supabase змінні у .env — інструкція є в README.'); setStatus('Зберігаємо…'); const { error } = await supabase.from('site_content').upsert({ id: 'main', content, updated_at: new Date().toISOString() }); setStatus(error ? `Помилка: ${error.message}` : 'Збережено ✓') }
  const upload = async (event: ChangeEvent<HTMLInputElement>, assign: (url: string) => void) => { const file = event.target.files?.[0]; if (!file) return; if (!supabase) return setStatus('Спершу підключіть Supabase.'); setStatus('Завантажуємо фото…'); const path = `${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; const { error } = await supabase.storage.from('anniversary-media').upload(path, file, { upsert: false }); if (error) return setStatus(`Помилка: ${error.message}`); assign(supabase.storage.from('anniversary-media').getPublicUrl(path).data.publicUrl); setStatus('Фото додано — не забудьте зберегти.') }
  if (!supabase) return <main className="admin-shell"><h1>CMS ще не підключена</h1><p>Додайте <code>VITE_SUPABASE_URL</code> та <code>VITE_SUPABASE_ANON_KEY</code> до <code>.env</code>, потім перезапустіть сайт. У README є покрокова інструкція.</p></main>
  if (!session) return <main className="admin-login"><p className="eyebrow">ПРИВАТНИЙ РЕДАКТОР</p><h1>ВХІД ДО <em>ІСТОРІЇ.</em></h1><form onSubmit={async e => { e.preventDefault(); const { error } = await supabase!.auth.signInWithPassword({ email, password }); setStatus(error ? error.message : '') }}><label>Електронна пошта<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Пароль<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label><button className="primary">УВІЙТИ</button>{status && <p>{status}</p>}</form></main>
  const list = content[tab as keyof Content] as unknown[]
  const remove = (index: number) => change({ ...content, [tab]: (list as unknown[]).filter((_, i) => i !== index) })
  const move = (index: number, step: number) => { const target = index + step; if (target < 0 || target >= list.length) return; const x = [...list]; [x[index], x[target]] = [x[target], x[index]]; change({ ...content, [tab]: x }) }
  const photoInput = (set: (url: string) => void, current?: string) => <label className="photo-field">{current && <img src={current} alt="Попередній перегляд"/>}<span>Змінити фото</span><input type="file" accept="image/*" onChange={e => upload(e, set)}/></label>
  return <main className="admin-shell"><header className="admin-head"><div><p className="eyebrow">АНДРІЙ × АНАСТАСІЯ</p><h1>РЕДАКТОР <em>ІСТОРІЇ.</em></h1></div><button className="secondary" onClick={() => supabase!.auth.signOut()}>ВИЙТИ</button></header><nav className="admin-nav">{sections.map(([id,icon,label]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{icon}<span>{label}</span></button>)}</nav><section className="editor">{tab === 'settings' ? <Settings content={content} change={change}/> : tab === 'letter' ? <Letter content={content} change={change}/> : <Collection content={content} tab={tab} items={list} change={change} remove={remove} move={move} photoInput={photoInput}/>}<div className="savebar"><span>{status}</span><button className="primary" onClick={save}>ЗБЕРЕГТИ ЗМІНИ</button></div></section></main>
}

function Settings({ content, change }: { content: Content; change: (c: Content) => void }) { const set = (key: keyof Content['couple'], value: string) => change({ ...content, couple: { ...content.couple, [key]: value } }); return <><h2>Налаштування</h2><p>Ці дані з’являються на головному екрані та у футері.</p><div className="field-grid"><label>Ім’я дружини<input value={content.couple.wife} onChange={e => set('wife',e.target.value)}/></label><label>Ім’я чоловіка<input value={content.couple.husband} onChange={e => set('husband',e.target.value)}/></label><label>Дата весілля<input type="date" value={content.couple.date} onChange={e => set('date',e.target.value)}/></label><label>Дата річниці<input type="date" value={content.couple.anniversary} onChange={e => set('anniversary',e.target.value)}/></label></div></> }
function Letter({ content, change }: { content: Content; change: (c: Content) => void }) { return <><h2>Лист</h2><p>Пишіть абзацами. Переноси рядків збережуться на сайті.</p><label>Текст листа<textarea rows={14} value={content.letter} onChange={e => change({ ...content, letter: e.target.value })}/></label><article className="letter-preview"><p>{content.letter}</p></article></> }
function Collection({ content, tab, items, change, remove, move, photoInput }: { content: Content; tab: string; items: unknown[]; change: (c: Content) => void; remove: (i:number) => void; move: (i:number,s:number) => void; photoInput: (set:(url:string)=>void,current?:string)=>ReactNode }) {
  const title: Record<string,string> = { milestones:'Наша історія',months:'Спогади',places:'Місця',achievements:'Досягнення',reasons:'Чому я тебе люблю',commits:'Git log' }
  const examples: Record<string,unknown> = { milestones:{icon:'✦',title:'Нова подія',date:'ДАТА',text:'Короткий опис',image:''}, months:{month:'НОВИЙ СПОГАД',image:'',caption:'Підпис'}, places:{place:'Нове місце',date:'ДАТА',note:'Спогад',image:''}, achievements:['06','НОВЕ ДОСЯГНЕННЯ','Опис'], reasons:'Нова причина', commits:['2026-01-01','new_memory'] }
  const update = (index: number, value: unknown) => change({ ...content, [tab]: items.map((x,i) => i === index ? value : x) })
  const add = () => change({ ...content, [tab]: [...items, clone(examples[tab])] })
  return <><h2>{title[tab]}</h2><p>Редагуйте картки, а стрілками змінюйте їхній порядок.</p>{items.map((item, i) => { const hasImage = typeof item === 'object' && item !== null && 'image' in item; const image = hasImage ? (item as {image:string}).image : undefined; return <article className="edit-card" key={i}><div className="order"><button onClick={() => move(i,-1)} aria-label="Перемістити вище">↑</button><button onClick={() => move(i,1)} aria-label="Перемістити нижче">↓</button></div><label className="json-edit">Картка {i + 1}<textarea rows={tab === 'reasons' ? 3 : 9} value={typeof item === 'string' ? item : JSON.stringify(item,null,2)} onChange={e => { try { update(i, tab === 'reasons' ? e.target.value : JSON.parse(e.target.value)) } catch { /* keep typing until JSON is valid */ } }}/></label>{hasImage && photoInput(url => update(i, { ...(item as object), image: url }), image)}<button className="danger" onClick={() => remove(i)}>Видалити</button></article> })}<button className="secondary" onClick={add}>+ ДОДАТИ</button><p className="helper">Фото з телефона одразу завантажується й показується у прев’ю. Потім натисніть «Зберегти зміни».</p></> }
